config/routes.rb
Rails.application.routes.draw do
    
    get '/' => 'high_voltage/pages#show', id: 'home', as: :home

    get '/' => 'high_voltage/pages#show', id: 'home', as: :about
    
    get "users/new_release" => 'users#new_release', :as => :new_release

    get "users/:id/ride_map" => 'users#map', :as => :ride_map

    get "/users/:user_id/join/:id" => "carpools#join_carpool", :as => :join_carpool

    get "/companies/:company_id/users/:id/calendar" => "users#calendar", as: :calendar
    

    resources :companies do
        resources :sessions, only: [:create, :destroy, :new]
        resources :users do
          resources :carpools
        end
    end
end

=begin
Prefix Verb   URI Pattern                                 Controller#Action
                GET    /                                           high_voltage/pages#show {:id=>"home"}
    new_release GET    /users/new_release(.:format)                users#new_release
       sessions POST   /sessions(.:format)                         sessions#create
    new_session GET    /sessions/new(.:format)                     sessions#new
        session DELETE /sessions/:id(.:format)                     sessions#destroy
  user_carpools GET    /users/:user_id/carpools(.:format)          carpools#index
                POST   /users/:user_id/carpools(.:format)          carpools#create
new_user_carpool GET    /users/:user_id/carpools/new(.:format)      carpools#new
edit_user_carpool GET    /users/:user_id/carpools/:id/edit(.:format) carpools#edit
   user_carpool GET    /users/:user_id/carpools/:id(.:format)      carpools#show
                PATCH  /users/:user_id/carpools/:id(.:format)      carpools#update
                PUT    /users/:user_id/carpools/:id(.:format)      carpools#update
                DELETE /users/:user_id/carpools/:id(.:format)      carpools#destroy
     user_rides GET    /users/:user_id/rides(.:format)             rides#index
                POST   /users/:user_id/rides(.:format)             rides#create
  new_user_ride GET    /users/:user_id/rides/new(.:format)         rides#new
 edit_user_ride GET    /users/:user_id/rides/:id/edit(.:format)    rides#edit
      user_ride GET    /users/:user_id/rides/:id(.:format)         rides#show
                PATCH  /users/:user_id/rides/:id(.:format)         rides#update
                PUT    /users/:user_id/rides/:id(.:format)         rides#update
                DELETE /users/:user_id/rides/:id(.:format)         rides#destroy
          users GET    /users(.:format)                            users#index
                POST   /users(.:format)                            users#create
       new_user GET    /users/new(.:format)                        users#new
      edit_user GET    /users/:id/edit(.:format)                   users#edit
           user GET    /users/:id(.:format)                        users#show
                PATCH  /users/:id(.:format)                        users#update
                PUT    /users/:id(.:format)                        users#update
                DELETE /users/:id(.:format)                        users#destroy
           page GET    /pages/*id                                  high_voltage/pages#show
=end

app/models/user.rb
class User < ActiveRecord::Base
    
    belongs_to :company
    
    has_many :rides, -> { includes :carpool }, dependent: :destroy
    
    # has_many :addresses, through: :rides, source: :lng_lat
    
    has_many :carpools, -> {uniq}, through: :rides, source: :carpool, dependent: :destroy

    has_many :driver_rides, -> {drivers}, class_name: 'Ride', dependent: :destroy
    
    has_many :passenger_rides, -> {passengers}, class_name: 'Ride'
    
    has_many :driver_carpools, -> {uniq}, through: :driver_rides, source: :carpool, dependent: :destroy

    has_many :passenger_carpools, -> {uniq}, through: :passenger_rides, source: :carpool
    
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]

    has_secure_password

    # after_validation :lnglats, unless: "rides.empty?"

    def addresses
        rides.select(:address_str){ |ride| ride.longitude.present? }
    end

    def lnglats
        rides.select(:longitude, :latitude){ |ride| ride.longitude.present? }
    end

    def pickup_lnglats
        passenger_rides.select(:longitude, :latitude) { |ride| ride.longitude.present? }
    end

    def driver_lnglats
        driver_rides.select(:longitude, :latitude) { |ride| ride.longitude.present? }
    end

    def start_time
        Date.today    
    end

    def appointments
        driver_carpools + passenger_carpools
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
  end

  def show
    @loc = request.location
    @user = User.includes(:company).find(params[:id])
    @available_rides = Kaminari.paginate_array(Carpool.available_rides(@user)).page(params[:page]).per(10)
    
  end

  def destroy
  end

  def new_release
    respond_to do |format|
        format.html
        format.js
    end
  end

  def map
    @user = User.includes(:company).find(params[:id])
    @cpools = Carpool.available_rides(@user)
    @cp2= @cpools.select{ |cp| cp.date.day >= Date.today.day }
    # @available_rides = Kaminari.paginate_array(Carpool.available_rides(@user)).page(params[:page]).per(20)    
    
    @hash = Gmaps4rails.build_markers(@cp2) do |cpool, marker|
    # @hash = Gmaps4rails.build_markers(@cpools) do |cpool, marker|
      marker.lat cpool.latitude
      marker.lng cpool.longitude
      # marker.infowindow "#{cpool.name} is leaving at #{cpool.date} and has #{cpool.seats_remaining} seats open"
      marker.infowindow render_to_string(:partial => "/users/info_map", :locals => { :object => cpool, user: @user})
    end
  end

  def calendar
    @user = User.includes(:company).find(params[:id])
    @meetings = @user.appointments
    render "_driver_cal"
  end

end

app/views/users/_available_rides.html.erb
<div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr >
          <th class="text-center">Join Carpool</th>
          <th class="text-center">Driver Name</th>
          <th class="text-center">Group Name</th>
          <th class="text-center">Date Time</th>
          <th class="text-center">Spaces Left</th>
        </tr>
      </thead>
      <tbody id="available_rides_list text-center">
        <% available_rides.each do |po_ride| %>
         <tr class="ridesrow">
           <!-- <td><a href="#" class="btn btn-success btn-sm">Join</a></td> -->
           <td><%= link_to "+", join_carpool_path(user, po_ride), class: "btn btn-sm btn-default joinbtn" %></td>
           <td class="text-center"><%= link_to po_ride.driver.name, company_user_path(user.company, po_ride.driver) %></td>
           <td class="text-center"><%= link_to po_ride.name, company_user_carpool_path(user.company, po_ride.driver, po_ride) %></td>
           <td class="text-center"><%= po_ride.date.to_formatted_s(:short) %></td>
           <td class="text-center"><%= po_ride.seats_remaining %></td>
         </tr> 
        <% end -%> 
      </tbody>
    </table>
</div>
<hr>

app/views/users/_carpool_create.html.erb
<div id="create_drive" class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" id="close_modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= form_for user.driver_carpools.new, html:{class: 'form-signin'}, url: company_user_carpools_path(user.company, user) do |f| %>
          <h2 class="form-signin-heading">Create Ride</h2>
          
          <div class="form-group">
            <%= f.label :name, class: 'sr-only'%>
            <%= f.text_field :name, class: 'form-control', :placeholder => "Carpool Name" %>
          </div>
          <div class="form-group">
            <%= f.label :date, class: 'sr-only'%>
            
            <%= f.text_field :date, class: "datepicker" %>
          </div>
          <div class="form-group">
            <%= f.label :capacity, class: 'sr-only'%>
            <%= f.number_field :capacity %>
          </div>
          <div class="modal-footer">
            <%= f.submit "Create Drive", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_driver_cal.html.erb
<%= month_calendar day_names: "date.day_names", events: @meetings, header: {class: "calendar-header"}, table: {class: "table table-bordered"}, tr: {class: "calendar-row"}, td: {class: "day"} do |date, meetings| %>
    <ul class="list-group">
      <% meetings.each do |meeting| %>
          <li class="list-group-item">
            <%= link_to meeting.name, company_user_carpool_path(@user.company, meeting, meeting.driver) %> <span class="pull-right"><%= meeting.time %></span>
          </li>
          
      <% end %>
    </ul>
    <div class="clearfix"></div>
    <span class="pull-right">
        <%= date %>
    </span>

<% end %>

app/views/users/_driver_rides.html.erb
<h2 class="center">Driver Rides</h2>
<div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Spaces Left</th>
          <th>Driver Name</th>
          <th>Group Name</th>
          <th>Date Time</th>
        </tr>
      </thead>
      <tbody>
        <% user.driver_carpools.each do |po_ride| %>
         <% if po_ride.driver.nil? %>
         <% else %>
           <tr>
             <td><%= po_ride.seats_remaining %></td>
             <td><%= po_ride.driver.name %></td>
             <td><%= po_ride.name %></td>
             
             <td><%= po_ride.date %></td>
           </tr> 
          <% end -%>        
        <% end -%>        
      </tbody>
    </table>
</div>

app/views/users/_info_map.html.erb
<ul class="list-group">
  <li class="list-group-item">
    <span>Carpool: </span>
    <span class="pull-right">
        <%= link_to object.name, company_user_carpool_path(user.company, object.driver, object) %>
    </span>
  </li>
  <li class="list-group-item">
    <span class="badge"><%= object.seats_remaining %></span>
    <%= "Open Seats:     #{}" %>
  </li>
  <li class="list-group-item">
    <span>Date: </span>
    <span class="pull-right">
        <%= object.date.to_formatted_s(:short) %>
    </span>
  </li>
  <li class="list-group-item">
    <span>Driver: </span>
    <span class="pull-right">
        <%= link_to object.driver.name, company_user_path(user.company, object.driver) %>
    </span>
  </li>
  <%= link_to "Join Ride", join_carpool_path(user, object), class: "btn btn-sm btn-success btn-block" %>
</ul>

app/views/users/_join.html.erb
<span class="pull-right">
    <% if current_user && !post.likers.include?(current_user) %>
      <%= form_for :like, html: {  class: 'like-form form form-inline pull-right'}, method: :post,  url: post_likes_path(post.id) do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :post_id, value: post.id %>
        
        <button class="pull-right btn btn-default btn-sm">
          <%=post.likes.count%>
        </button>
        <%= f.submit "+", class: "btn btn-success btn-sm like-button pull-right" %>
      <%end%>
    <%else%>
      <button class="pull-right btn btn-default btn-sm">
        <%=post.likes.count%>
      </button>
    <%end%>
</span>

app/views/users/_new_release.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
  <ul>
    <li>things</li>
    <li>more things</li>
    <li>extra things</li>
  </ul>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <button class="btn btn-primary">Save changes</button>
</div>

app/views/users/_passenger_rides.erb
<h2 class="center">Passenger Rides</h2>
<div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Spaces Left</th>
          <th>Driver Name</th>
          <th>Group Name</th>
          <th>Distance</th>
          <th>Date Time</th>
        </tr>
      </thead>
      <tbody>
        <% user.passenger_carpools.each do |po_ride| %>
          <% if po_ride.driver.nil? %>
          <% else %>
             <tr>
               <td><%= po_ride.seats_remaining %></td>
               <td><%= po_ride.driver.name %></td>
               <td><%= po_ride.name %></td>
               <td><%= po_ride.driver_ride.distance_to( [po_ride.passenger_rides.where(user_id: user.id).first.latitude, po_ride.passenger_rides.where(user_id: user.id).first.longitude] ).round(3) %></td>
               <td><%= po_ride.date %></td>  
             </tr> 
          <% end -%>        
        <% end -%>        
      </tbody>
    </table>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/map.html.erb
<div >
  <div id="map"></div>
</div>

<hr>
<%= render partial: "available_rides", locals: {available_rides: @cpools, user: @user} %>

<%= @cpools.count %>
<%= @cp2.count %>
<hr>
<% @cp2.each do |cpool| %>
    <%= cpool.longitude %>
    <br>
    <%= cpool.latitude %>
    <br><br>
<% end -%>
<hr>

<script type="text/javascript">
    $(document).ready(function(){
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
          markers = handler.addMarkers(<%=raw @hash.to_json %>);
          
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
        
    });
</script>

app/views/users/new.html.erb
<p>This is a gift.</p>

app/views/users/new_release.js.erb
$('#modal-window').html("<%= escape_javascript(render 'users/new_release') %>");

app/views/users/show.html.erb
<div class="jumbotron">
  <h1>Jumbotron</h1>
  <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <div class="btn-group btn-group-justified">
    <!-- <a href="#" id="create_ride_link" class="btn btn-success btn-lg">I Need A Ride</a> -->
    <a href="#" id="create_drive_link" class="btn btn-primary btn-lg">I'll Drive</a>
    <!-- <a href="#" id="find_ride_link" class="btn btn-info btn-lg">I Need A Ride</a> -->
    <%= link_to "Find Ride", ride_map_path, class: "btn btn-info btn-lg" %>
  </div>
</div>


<%= @loc.latitude %>
<%= @loc.longitude %>
<%= @loc.address %>
<!-- <hr> -->


<%= render partial: "carpool_create", locals: {user: @user} %> 
<%= render partial: "find_ride", locals: {user: @user} %> 

<hr>

<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-justified" id="myTabs" role="tablist">
    <li role="presentation" class="active"><a href="#all_available" aria-controls="all_available" role="tab" data-toggle="tab">Available Rides</a></li>
    <li role="presentation"><a href="#passenger_rides" aria-controls="passenger_rides" role="tab" data-toggle="tab">Passenger Carpools</a></li>
    <li role="presentation"><a href="#driver_rides" aria-controls="driver_rides" role="tab" data-toggle="tab">Driver Carpools</a></li>
    <!-- <li role="presentation"><a href="#driver_cal" aria-controls="driver_cal" role="tab" data-toggle="tab">Calendar</a></li> -->
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="all_available">
        <%= render partial: "available_rides", locals: {available_rides: @available_rides, user: @user} %>
    </div>
    <div role="tabpanel" class="tab-pane" id="passenger_rides">
        <%= render partial: "passenger_rides", locals: {user: @user} %>
    </div>
    <div role="tabpanel" class="tab-pane" id="driver_rides">
        <%= render partial: "driver_rides", locals: {user: @user} %>
    </div>
    
  </div>
</div>