config/routes.rb
Rails.application.routes.draw do
    
    get '/' => 'high_voltage/pages#show', id: 'home', as: :home

    get '/' => 'high_voltage/pages#show', id: 'home', as: :about
    
    get "users/new_release" => 'users#new_release', :as => :new_release

    get "users/:id/ride_map" => 'users#map', :as => :ride_map

    get "/users/:user_id/join/:id" => "carpools#join_carpool", :as => :join_carpool

    get "/companies/:company_id/users/:id/calendar" => "users#calendar", as: :calendar
    

    resources :companies do
        resources :sessions, only: [:create, :destroy, :new]
        resources :users do
          resources :carpools
        end
    end
end

=begin
Prefix Verb   URI Pattern                                 Controller#Action
                GET    /                                           high_voltage/pages#show {:id=>"home"}
    new_release GET    /users/new_release(.:format)                users#new_release
       sessions POST   /sessions(.:format)                         sessions#create
    new_session GET    /sessions/new(.:format)                     sessions#new
        session DELETE /sessions/:id(.:format)                     sessions#destroy
  user_carpools GET    /users/:user_id/carpools(.:format)          carpools#index
                POST   /users/:user_id/carpools(.:format)          carpools#create
new_user_carpool GET    /users/:user_id/carpools/new(.:format)      carpools#new
edit_user_carpool GET    /users/:user_id/carpools/:id/edit(.:format) carpools#edit
   user_carpool GET    /users/:user_id/carpools/:id(.:format)      carpools#show
                PATCH  /users/:user_id/carpools/:id(.:format)      carpools#update
                PUT    /users/:user_id/carpools/:id(.:format)      carpools#update
                DELETE /users/:user_id/carpools/:id(.:format)      carpools#destroy
     user_rides GET    /users/:user_id/rides(.:format)             rides#index
                POST   /users/:user_id/rides(.:format)             rides#create
  new_user_ride GET    /users/:user_id/rides/new(.:format)         rides#new
 edit_user_ride GET    /users/:user_id/rides/:id/edit(.:format)    rides#edit
      user_ride GET    /users/:user_id/rides/:id(.:format)         rides#show
                PATCH  /users/:user_id/rides/:id(.:format)         rides#update
                PUT    /users/:user_id/rides/:id(.:format)         rides#update
                DELETE /users/:user_id/rides/:id(.:format)         rides#destroy
          users GET    /users(.:format)                            users#index
                POST   /users(.:format)                            users#create
       new_user GET    /users/new(.:format)                        users#new
      edit_user GET    /users/:id/edit(.:format)                   users#edit
           user GET    /users/:id(.:format)                        users#show
                PATCH  /users/:id(.:format)                        users#update
                PUT    /users/:id(.:format)                        users#update
                DELETE /users/:id(.:format)                        users#destroy
           page GET    /pages/*id                                  high_voltage/pages#show
=end

app/views/pages/_gmap.html.erb
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

app/views/pages/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Company Carpool</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Help</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-sm-11 col-sm-offset-1">
    
    <div class="col-sm-3 panel panel-default killpad">
      <a href="#" id="create_company_link" class="btn btn-info btn-me btn-lg" >Create Company</a>
    </div>

    <div class="col-sm-7 col-sm-offset-1 killpad">
      <div class="form-group">
        <input class="form-control input-lg text-center" id="comp_filter" type="text" value="Search Companies">
      </div>
    </div>

  </div>  
</div>

<hr><div class="clearfix"></div>

<!-- <div class="row">
  <div class="col-sm-12">
    <h2 class="text-center">Companies</h2>
  </div>
</div>

<br><div class="clearfix"></div>
 -->
<div class="company_list">
  <% Company.all.each_slice(3) do |comps| %>
    <div class="row">
      <div class="col-sm-11 col-sm-offset-1">
        <% comps.each_with_index do |comp, index| %>
          <% if index == 0 %>
            <div class="col-sm-3 panel panel-default">
          <% else %>
            <div class="col-sm-3 col-sm-offset-1 panel panel-default">
          <% end -%>
            <!-- <div class="panel-heading"></div> -->
            <div class="panel-body text-center">
              <%= link_to comp.name.upcase, company_path(comp) %>
            </div>
          </div>

        <% end -%>
      </div>
    
    </div>

  <% end -%>
</div>

<%= render partial: "companies/new" %> 