config/routes.rb
Rails.application.routes.draw do
    
    get '/' => 'high_voltage/pages#show', id: 'home', as: :home

    get '/' => 'high_voltage/pages#show', id: 'home', as: :about
    
    get "users/new_release" => 'users#new_release', :as => :new_release

    get "users/:id/ride_map" => 'users#map', :as => :ride_map

    get "/users/:user_id/join/:id" => "carpools#join_carpool", :as => :join_carpool

    get "/companies/:company_id/users/:id/calendar" => "users#calendar", as: :calendar
    

    resources :companies do
        resources :sessions, only: [:create, :destroy, :new]
        resources :users do
          resources :carpools
        end
    end
end

=begin
Prefix Verb   URI Pattern                                 Controller#Action
                GET    /                                           high_voltage/pages#show {:id=>"home"}
    new_release GET    /users/new_release(.:format)                users#new_release
       sessions POST   /sessions(.:format)                         sessions#create
    new_session GET    /sessions/new(.:format)                     sessions#new
        session DELETE /sessions/:id(.:format)                     sessions#destroy
  user_carpools GET    /users/:user_id/carpools(.:format)          carpools#index
                POST   /users/:user_id/carpools(.:format)          carpools#create
new_user_carpool GET    /users/:user_id/carpools/new(.:format)      carpools#new
edit_user_carpool GET    /users/:user_id/carpools/:id/edit(.:format) carpools#edit
   user_carpool GET    /users/:user_id/carpools/:id(.:format)      carpools#show
                PATCH  /users/:user_id/carpools/:id(.:format)      carpools#update
                PUT    /users/:user_id/carpools/:id(.:format)      carpools#update
                DELETE /users/:user_id/carpools/:id(.:format)      carpools#destroy
     user_rides GET    /users/:user_id/rides(.:format)             rides#index
                POST   /users/:user_id/rides(.:format)             rides#create
  new_user_ride GET    /users/:user_id/rides/new(.:format)         rides#new
 edit_user_ride GET    /users/:user_id/rides/:id/edit(.:format)    rides#edit
      user_ride GET    /users/:user_id/rides/:id(.:format)         rides#show
                PATCH  /users/:user_id/rides/:id(.:format)         rides#update
                PUT    /users/:user_id/rides/:id(.:format)         rides#update
                DELETE /users/:user_id/rides/:id(.:format)         rides#destroy
          users GET    /users(.:format)                            users#index
                POST   /users(.:format)                            users#create
       new_user GET    /users/new(.:format)                        users#new
      edit_user GET    /users/:id/edit(.:format)                   users#edit
           user GET    /users/:id(.:format)                        users#show
                PATCH  /users/:id(.:format)                        users#update
                PUT    /users/:id(.:format)                        users#update
                DELETE /users/:id(.:format)                        users#destroy
           page GET    /pages/*id                                  high_voltage/pages#show
=end

app/models/company.rb
class Company < ActiveRecord::Base

    has_many :users

    has_many :carpools, through: :users, source: :carpools    
    
    geocoded_by :address   # can also be an IP address
    after_validation :geocode
    
    has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_file_name :logo, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
    
    has_secure_password

    def address
        [street, city, state, country].compact.join(', ')
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    
    def new
            
    end    
    
    def show
        @comp = Company.find(params[:id])
    end

    def create
       @comp = Company.create(company_params)
       redirect_to company_path(@comp)
    end

    private
        def company_params
            params.require(:company).permit(:name, :email, :password, :password_confirmation, :street, :city, :state, :country)
        end
end

app/views/companies/_new.html.erb
<div id="create_company" class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" id="close_modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Create Your Company</h4>
      </div>
      <div class="modal-body">
        <%= form_for :company, html:{class: 'form-horizontal'}, url: companies_path do |f| %>
          <fieldset>
            <div class="form-group">
              <%= f.label :name, class: 'col-lg-2 control-label'%>
              <div class="col-lg-8">
                <%= f.text_field :name, required: true, class: 'form-control', :placeholder => "Company Name" %>              
              </div>
            </div>
            
            <div class="form-group">
              <%= f.label :email, class: 'col-lg-2 control-label'%>
              <div class="col-lg-8">
                <%= f.text_field :email, required: true, class: 'form-control', :placeholder => "Email"%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :password, class: 'col-lg-2 control-label'%>
              <div class="col-lg-8">
                <%= f.password_field :password, required: true, class: 'form-control', :placeholder => "Password"%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation, class: 'col-lg-2 control-label'%>
              <div class="col-lg-8">
                <%= f.password_field :password_confirmation, required: true, class: 'form-control', :placeholder => "Confirm Password" %>
              </div>
            </div>
            
            <div class="form-group">
              <%= f.label :country, class: 'col-lg-2 control-label'%>
              <div class="col-lg-8">
                <%= f.text_field :country, required: true, class: 'form-control', :placeholder => "Country"%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :street, class: 'col-lg-2 control-label'%>
              <div class="col-lg-8">
                <%= f.text_field :street, required: true, class: 'form-control', :placeholder => "Street and #"%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :city, class: 'col-lg-2 control-label'%>
              <div class="col-lg-8">
                <%= f.text_field :city, required: true, class: 'form-control', :placeholder => "City" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :state, class: 'col-lg-2 control-label'%>
              <div class="col-lg-8">
                <%= f.text_field :state, required: true, class: 'form-control', :placeholder => "State/Canton"%>
              </div>
            </div>

            <div class="modal-footer">
              <%= f.submit "Create Company", class: 'btn btn-primary' %>
            </div>

          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<%= form_for :user, html:{class: 'form-signin'}, url: company_sessions_path(@comp) do |f| %>
  <h2 class="form-signin-heading">Please sign in</h2>
    
  <div class="form-group">
    <%= f.label :email , class: 'sr-only'%>
    <%= f.email_field :email, class: 'form-control', :placeholder => "Email address" %>
  </div>
  <div class="form-group">
    <%= f.label :password, class: 'sr-only'%>
    <%= f.password_field :password, class: 'form-control', :placeholder => "Password" %>
  </div>

  <div class="form-group">
    <%= f.submit "Sign In", class: 'btn btn-primary' %>
  </div>

<% end %>