config/routes.rb
Rails.application.routes.draw do
    
    get '/' => 'high_voltage/pages#show', id: 'home', as: :home

    get '/' => 'high_voltage/pages#show', id: 'home', as: :about
    
    get "users/new_release" => 'users#new_release', :as => :new_release

    get "users/:id/ride_map" => 'users#map', :as => :ride_map

    get "/users/:user_id/join/:id" => "carpools#join_carpool", :as => :join_carpool

    get "/companies/:company_id/users/:id/calendar" => "users#calendar", as: :calendar
    

    resources :companies do
        resources :sessions, only: [:create, :destroy, :new]
        resources :users do
          resources :carpools
        end
    end
end

=begin
Prefix Verb   URI Pattern                                 Controller#Action
                GET    /                                           high_voltage/pages#show {:id=>"home"}
    new_release GET    /users/new_release(.:format)                users#new_release
       sessions POST   /sessions(.:format)                         sessions#create
    new_session GET    /sessions/new(.:format)                     sessions#new
        session DELETE /sessions/:id(.:format)                     sessions#destroy
  user_carpools GET    /users/:user_id/carpools(.:format)          carpools#index
                POST   /users/:user_id/carpools(.:format)          carpools#create
new_user_carpool GET    /users/:user_id/carpools/new(.:format)      carpools#new
edit_user_carpool GET    /users/:user_id/carpools/:id/edit(.:format) carpools#edit
   user_carpool GET    /users/:user_id/carpools/:id(.:format)      carpools#show
                PATCH  /users/:user_id/carpools/:id(.:format)      carpools#update
                PUT    /users/:user_id/carpools/:id(.:format)      carpools#update
                DELETE /users/:user_id/carpools/:id(.:format)      carpools#destroy
     user_rides GET    /users/:user_id/rides(.:format)             rides#index
                POST   /users/:user_id/rides(.:format)             rides#create
  new_user_ride GET    /users/:user_id/rides/new(.:format)         rides#new
 edit_user_ride GET    /users/:user_id/rides/:id/edit(.:format)    rides#edit
      user_ride GET    /users/:user_id/rides/:id(.:format)         rides#show
                PATCH  /users/:user_id/rides/:id(.:format)         rides#update
                PUT    /users/:user_id/rides/:id(.:format)         rides#update
                DELETE /users/:user_id/rides/:id(.:format)         rides#destroy
          users GET    /users(.:format)                            users#index
                POST   /users(.:format)                            users#create
       new_user GET    /users/new(.:format)                        users#new
      edit_user GET    /users/:id/edit(.:format)                   users#edit
           user GET    /users/:id(.:format)                        users#show
                PATCH  /users/:id(.:format)                        users#update
                PUT    /users/:id(.:format)                        users#update
                DELETE /users/:id(.:format)                        users#destroy
           page GET    /pages/*id                                  high_voltage/pages#show
=end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes alert">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %> text-center lead">
        <%= value %>
      </div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "", home_path, class: "navbar-brand glyphicon glyphicon-home" %>
      <!-- <span class="glyphicon glyphicon-home" aria-hidden="true"></span> -->
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "About", about_path %>
        </li>
        <% if current_user != nil %>
          <!-- <li><span class="glyphicon glyphicon-user"></span></li> -->
          <li>
            <%= link_to current_user.name.capitalize, company_user_path(current_user.company, current_user) %>
          </li>
          
          <li>
            <%= link_to "Calendar", calendar_path(current_user.company, current_user) %>
          </li>
          
          <li class="pull-right">
            <%= link_to "Log out", company_session_path(current_user.company, current_user), method: :delete %>
          </li>
        <% end -%>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
    </div>
  </div>
</nav>

app/views/application/index.html.erb
<div ng-view=""></div>